name: intershop
services:
  app:
    container_name: intershop
    image: intershop
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8085:8080"
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      PAYSRV_URL: http://paysrv:8080
      SPRING_DATA_REDIS_URL: redis://redis:6379
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/intershopdb
      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak
      KC_HTTP_ENABLED: "true"
      # Включаем импорт реалма при старте
      KC_IMPORT: /opt/keycloak/data/import/dev-realm.json
    command: ["start-dev", "--import-realm"]
    ports:
      - "9087:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
  paysrv:
    image: paysrv
    build:
      context: .
      dockerfile: paysrv/Dockerfile
    ports:
      - "9086:8080"
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      SERVER_PORT: 8080
  postgres:
    image: postgres:17.2-alpine3.20
    restart: always
    # set shared memory limit (reason: https://hub.docker.com/_/postgres)
    shm_size: 128mb
    ports:
      - "9432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      # run scripts for create user and database
      - ./app/src/main/resources/db/init:/docker-entrypoint-initdb.d
      - intershopdb-data:/var/lib/postgresql/data
  redis:
    image: redis:7.4.2-alpine3.21
    ports:
      - "9479:6379"
volumes:
  intershopdb-data:
