logging.level.org.example.intershop: DEBUG

# Не используем 8080, т.к. он может быть занят
server.port: 8085

spring:
  application:
    name: intershop
  r2dbc:
    username: javadev
    password: javadev
#  jpa:
#    # Логирование SQL, выполняемого Hibernate
#    show-sql: true
#    # При отсутствии явно указанного диалекта он определяется при старте приложения запросом к БД, отсутствие
#    # подключения к БД приведет к фатальной ошибке, если диалект указан - в логе будет игнорируемая ошибка
#    #database-platform: org.hibernate.dialect.PostgreSQLDialect
#

# Liquibase требует jdbc-драйвера, пока что отключил
#  # явно указан путь master-файла Liquibase (при отсутствии файла будет фатальная ошибка)
#  liquibase.change-log: classpath:/db/changelog/db.changelog-master.yaml
  # временный способ развертывания схемы (пока не восстановлена Liquibase)
  sql.init:
    encoding: utf-8
    mode: always
    schema-locations: classpath:db/schema.sql

  profiles.active: dev
