openapi: 3.0.3
info:
  title: Payment service API
  description: API сервиса платежей
  version: 1.0.0
tags:
  - name: payment
    description: Оплата покупок
paths:
  /api/accounts/{accountId}/balance:
    get:
      tags:
        - payment
      operationId: getBalance
      summary: Получить баланс на счете клиента
      parameters:
        - name: accountId
          in: path
          required: true
          description: Уникальный идентификатор счета клиента
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_-]+$'
            minLength: 1
            maxLength: 50
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
  /api/pay:
    put:
      tags:
        - payment
      operationId: pay
      summary: Оплатить покупку со счета клиента
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Purchase'
      responses:
        '200':
          description: Платеж выполнен
        '400':
          description: Некорректный запрос (в т.ч. недостаточно средств для выполнения платежа)
components:
  schemas:
    Balance:
      type: object
      properties:
        amount:
          type: number
          format: double
          example: 150.00
      required:
        - amount
    Purchase:
      type: object
      properties:
        accountId:
          type: string
          description: Идентификатор счета для списания
          pattern: '^[a-zA-Z0-9_-]+$'
          minLength: 1
          maxLength: 50
        amount:
          type: number
          format: double
          example: 150.00
      required:
        - accountId
        - amount
