logging:
  level:
    org.example.paysrv: DEBUG
    #org.springframework: DEBUG

spring:
  application:
    name: paysrv
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8087/realms/master

  profiles.active: dev
