logging:
  level:
    org.example.paysrv: DEBUG
    #org.springframework: DEBUG

spring:
  application:
    name: paysrv
  security:
    oauth2:
      client:
        registration:
          paysrv:
            client-id: paysrv
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/dev-realm

  profiles.active: dev

