# URL авторизационного сервера Keycloak
keycloak.url: http://localhost:8087

# Начальный баланс (для настройки упрощенной реализации)
paysrv.init.balance: 1000

# URL тестового платежного сервиса
server.port: 18086
